spring:
  datasource:
    url: jdbc:mysql://localhost:3306/humosoft_cnpm
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      maximum-pool-size: 10
      minimum-idle: 5
  jpa:
    hibernate:
      ddl-auto: create  # Có thể là 'create', 'update', 'create-drop' hoặc 'validate'
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect  # Thay đổi tại đây
    show-sql: true  # Hiển thị SQL trong console khi ứng dụng chạy
