spring:
  datasource:
    url: jdbc:mysql://localhost:3306/humosoft_cnpm?useSSL=false&serverTimezone=UTC
    username: root
    password: ""  # Mật khẩu của bạn ở đây
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      maximum-pool-size: 10  # Kích thước tối đa của pool kết nối
      minimum-idle: 5  # Số kết nối tối thiểu trong pool
      idle-timeout: 30000  # Thời gian tối đa giữ kết nối không hoạt động trước khi đóng
      max-lifetime: 1800000  # Thời gian tối đa tồn tại của một kết nối trong pool
      connection-timeout: 30000  # Thời gian chờ kết nối trong pool trước khi ném lỗi

  jpa:
    hibernate:
      ddl-auto: update  # "create" sẽ tạo lại bảng mỗi lần ứng dụng khởi động. Dùng "validate" để chỉ kiểm tra cấu trúc bảng.
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect  # Dialect cho MySQL 8
    show-sql: true  # Hiển thị câu lệnh SQL trong log (tùy chọn)

  mail:
    host: smtp.gmail.com
    from: ${MAIL_FROM:vunguyen10112k4@gmail.com}  # Địa chỉ gửi email. Nếu có biến môi trường MAIL_FROM thì dùng, nếu không dùng mặc định.
    port: 587  # Cổng SMTP của Gmail
    username: vunguyen10112k4  # Tên người dùng (email)
    password: wwhh bopv lzll wxlf
  # Mật khẩu ứng dụng của Gmail (tạo từ tài khoản Google)
    properties:
      mail:
        smtp:
          auth: true  # Bật xác thực SMTP
          starttls:
            enable: true  # Kích hoạt STARTTLS cho kết nối bảo mật

  security:
    jwt:
      secret-key: Ewu4H0jzCNxXtoJS1D9YzLZ/zENfOLLdYQIudk+P5BLa66bFbXt2D/to55MViGnF  # Khóa bí mật dùng để mã hóa và giải mã JWT
      expiration: 86400000  # Thời gian hết hạn token (1 ngày - 86400000 ms)
      refresh-token:
        expiration: 604800000  # Thời gian hết hạn refresh token (7 ngày - 604800000 ms)
